## Color palette

# yellows:  dba355 d8a038 d8bd36 edd17d
# greens:   92ef92 6bbf3b 1cef5c 75b72d 9fea8f c6e84e c1f45a b8d613 fcf0b5 
# reds:     dd362a
# blues:    5b91c6 2a7d93 0bb1ed
# pinks:    bf0f73
# oranges:  ba500e ce8048
# teals:    40c491

###
### Special magic GitHub labels
###
- name: "good first issue"
  color: 7057ff
  description: "Good for newcomers"
- name: "help wanted"
  color: 008672
  description: "Extra attention is needed"

###
### Areas
###
- name: area/ux-cli
  color: 0bb1ed
  description: "Area: UX/CLI"
- name: area/core
  color: 0bb1ed
  description: "Area: Core"
- name: area/sdk
  color: 0bb1ed
  description: "Area: SDK"
- name: area/sidecar
  color: 0bb1ed
  description: "Area: Sidecar"
- name: area/sync-service
  color: 0bb1ed
  description: "Area: Sync Service"
- name: area/observability
  color: 0bb1ed
  description: "Area: Observability"
- name: area/runners
  color: 0bb1ed
  description: "Area: Runners"
- name: area/builders
  color: 0bb1ed
  description: "Area: Builders"
- name: area/infra
  color: 0bb1ed
  description: "Area: Infrastructure"
- name: area/specs
  color: 0bb1ed
  description: "Area: Specs"
- name: area/docs
  color: 0bb1ed
  description: "Area: Documentation"
- name: area/testing
  color: 0bb1ed
  description: "Area: Testing"
- name: area/ci
  color: 0bb1ed
  description: "Area: Continuous Integration"

###
### SDKs
###
- name: sdk/rust
  color: 0bb1ed
  description: "SDK: Rust"
- name: sdk/js
  color: 0bb1ed
  description: "SDK: Javascript"
- name: sdk/go
  color: 0bb1ed
  description: "SDK: Go"
- name: sdk/other
  color: 0bb1ed
  description: "SDK: Others"

###
### Kinds
###
- name: kind/bug
  color: c92712
  description: "Kind: Bug"
- name: kind/investigation
  color: fcf0b5
  description: "Kind: Investigation"
- name: kind/chore
  color: fcf0b5
  description: "Kind: Chore"
- name: kind/feature
  color: fcf0b5
  description: "Kind: Feature"
- name: kind/improvement
  color: fcf0b5
  description: "Kind: Improvement"
- name: kind/test
  color: fcf0b5
  description: "Kind: Test"
- name: kind/tracking-issue
  color: fcf0b5
  description: "Kind: Tracking Issue"
- name: kind/epic
  color: 3e4b9e
  description: "Kind: EPIC"
- name: kind/question
  color: fcf0b5
  description: "Kind: Question"
- name: kind/roadmap
  color: fcf0b5
  description: "Kind: Roadmap"
- name: kind/discussion
  color: fcf0b5
  description: "Kind: Discussion"

###
### Difficulties
###
- name: exp/beginner
  color: b2b7ff
  description: "Can be confidently tackled by newcomers, who are widely unfamiliar with testground."
- name: exp/novice
  color: 7886d7
  description: "A prexisting testground user should be able to pick this up."
- name: exp/intermediate
  color: 6574cd
  description: "Prior experience in having developed testground modules is likely helpful."
- name: exp/expert
  color: 5661b3
  description: "Suggests that having worked on the specific component affected by this issue is important."
- name: exp/wizard
  color: 2f365f
  description: "Requires extensive knowledge of the history, implications, ramifications of the issue."  

###
### Efforts
###
- name: effort/hours
  color: a0f0ed
  description: "Effort: One or Multiple Hours."
- name: effort/day
  color: 64d5ca
  description: "Effort: One Day."
- name: effort/days
  color: 4dc0b5
  description: "Effort: Multiple Days."
- name: effort/week
  color: 38a89d
  description: "Effort: One Week."
- name: effort/weeks
  color: 20504f
  description: "Effort: Multiple Weeks."  

###
### Impacts
###
- name: impact/regression
  color: f1f5f8
  description: "Impact: Regression"
- name: impact/api-breakage
  color: f1f5f8
  description: "Impact: API Breakage"
- name: impact/quality
  color: f1f5f8
  description: "Impact: Quality"
- name: impact/dx
  color: f1f5f8
  description: "Impact: Developer Experience"
- name: impact/test-flakiness
  color: f1f5f8
  description: "Impact: Test Flakiness"  

###
### Topics
###
- name: topic/interoperability
  color: bf0f73
  description: "Topic: Interoperability"
- name: topic/multi-language
  color: bf0f73
  description: "Topic: Multi-language"
- name: topic/specs
  color: bf0f73
  description: "Topic: Specs"
- name: topic/docs
  color: bf0f73
  description: "Topic: Documentation"
- name: topic/architecture
  color: bf0f73
  description: "Topic: Architecture"  

###
### Priorities
###
- name: P0
  color: dd362a
  description: "P0: Critical. This is a blocker. Drop everything else."
- name: P1
  color: ce8048
  description: "P1: Must be fixed."
- name: P2
  color: dbd81a
  description: "P2: Should be fixed."
- name: P3
  color: 9fea8f
  description: "P3: Might get fixed."

###
### Hints
###
- name: hint/needs-contributor
  color: 0623cc
  description: "Hint: Needs Contributor"
- name: hint/needs-triage
  color: 0623cc
  description: "Hint: Needs Triage"
- name: hint/needs-author-input
  color: 0623cc
  description: "Hint: Needs Author Input"
- name: hint/needs-team-input
  color: 0623cc
  description: "Hint: Needs Team Input"
- name: hint/needs-community-input
  color: 0623cc
  description: "Hint: Needs Community Input"
- name: hint/needs-docs
  color: 0623cc
  description: "Hint: Needs Docs"

###
### Statuses
###
- name: status/blocked
  color: edb3a6
  description: "Status: Blocked"

###
### Starmaps
###
- name: starmaps
  color: 27292c
  description: "https://www.starmaps.app/"
