notifications:
  email: false

language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

go:
  - 1.13.x

services:
  - docker
  - redis-server

stages:
  - build_check_test
  - run

jobs:
  include:
    - stage: build_check_test
      os: linux
      script:
        - go install github.com/golangci/golangci-lint/cmd/golangci-lint
        - golangci-lint run       # run a bunch of code checkers/linters in parallel
        - go build ./...          # build the project
        - go test -v -race ./...  # Run all the tests with the race detector enabled
        - go build .

    - stage: build_check_test
      os: windows
      script:
        - go install github.com/golangci/golangci-lint/cmd/golangci-lint
        - golangci-lint run       # run a bunch of code checkers/linters in parallel
        - go build ./...          # build the project
        - go test -v -race ./...  # Run all the tests with the race detector enabled
        - go build .

# Travis takes ages to allocate a macOS box, and the risk of something working with linux but not with macOS is low.
# We also currently don't have any tests that would catch any bugs.
#    - stage: test
#      os: osx
#      script:
#        - go install github.com/golangci/golangci-lint/cmd/golangci-lint
#        - golangci-lint run       # run a bunch of code checkers/linters in parallel
#        - go build ./...          # build the project
#        - go test -v -race ./...  # Run all the tests with the race detector enabled
#        - go build .

    #
    # Run two test plans as a smoke test
    #
    - stage: run
      name: "dht/find-peers linux - no docker"
      os: linux
      script:
        - go run dht/find-peers --builder=exec:go --runner=local:exec

    - stage: run
      name: "dht/find-peers linux - with docker"
      os: linux
      script:
        - go run main.go run dht/find-peers --builder=docker:go --runner=local:docker --build-cfg go_proxy_mode=direct

# Services are not supported on Travis (Docker + Redis) when in Mac OS X
#    - stage: run
#      name: "dht/find-peers osx - no docker"
#      os: osx
#      script:
#        - go run main.go run dht/find-peers --builder=exec:go --runner=local:exec

#    - stage: run
#      name: "dht/find-peers windows - no docker"
#      os: windows
#      script:
#        - go run main.go run dht/find-peers --builder=exec:go --runner=local:exec

# Services are not supported on Travis (Docker + Redis) when in Mac OS X
#    - stage: run
#      name: "dht/find-peers osx - with docker"
#      os: osx
#      script:
#        - go run main.go run dht/find-peers --builder=docker:go --runner=local:docker

# Services are not supported on Travis (Docker + Redis) when in Mac OS X
#    - stage: run
#      name: "dht/find-peers windows - with docker"
#      os: windows
#      script:
#        - go run main.go run dht/find-peers --builder=docker:go --runner=local:docker
