notifications:
  email: false

language: go

go:
  - 1.14.x

services:
  - docker
#  - redis-server

env:
  global:
    - GOTFLAGS="-race -coverprofile=coverage.txt -covermode=atomic"
    - GO111MODULE=on

cache:
  directories:
    - $HOME/gopath/pkg/mod
    - $HOME/docker_images  # https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-542672812

before_install:
  - docker load -i $HOME/docker_images/images.tar || true

before_cache:
  - docker save -o $HOME/docker_images/images.tar $(docker images -a -q)

jobs:
  include:
#    - stage: "tidy and prepare cache"
#      os: linux
#      script:
#        - make tidy
#        - git diff --exit-code
#        - make mod-download
#        - go mod graph
    - stage: "lint, build, test"
      os: linux
      name: "tidy and lint"
      script:
        - make tidy
        - git diff --exit-code
        - pushd .. && go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.23.6 && popd && make lint
    - name: "build recursive, build docker & test recursive"
      os: linux
      script:
        - make build-all
        - make docker
        - make test
    - name: "build on windows"
      os: windows
      script:
        - go build ./...

# Travis takes ages to allocate a macOS box, and the risk of something working with linux but not with macOS is low.
# We also currently don't have any tests that would catch any bugs.
#    - stage: test
#      os: osx
#      script:
#        - go install github.com/golangci/golangci-lint/cmd/golangci-lint
#        - golangci-lint run       # run a bunch of code checkers/linters in parallel
#        - go build ./...          # build the project
#        - go test -v -race ./...  # Run all the tests with the race detector enabled
#        - go build .

# This smoke run has been moved to the build_check_test_run to avoid having to rebuild the codebase.
#    #
#    # Run two test plans as a smoke test
#    #
#    - stage: run
#      name: "dht/find-peers linux - no docker"
#      os: linux
#        - go run main.go -vv run dht/find-peers --builder=exec:go --runner=local:exec --test-param timeout_secs=15
#      script:

# The docker build does not work properly on Travis.
#    - stage: run
#      name: "dht/find-peers linux - with docker"
#      os: linux
#      script:
#        - go run main.go -vv run dht/find-peers --builder=docker:go --runner=local:docker --build-cfg go_proxy_mode=direct

# Services are not supported on Travis (Docker + Redis) when in Mac OS X
#    - stage: run
#      name: "dht/find-peers osx - no docker"
#      os: osx
#      script:
#        - go run main.go run dht/find-peers --builder=exec:go --runner=local:exec

#    - stage: run
#      name: "dht/find-peers windows - no docker"
#      os: windows
#      script:
#        - go run main.go run dht/find-peers --builder=exec:go --runner=local:exec

# Services are not supported on Travis (Docker + Redis) when in Mac OS X
#    - stage: run
#      name: "dht/find-peers osx - with docker"
#      os: osx
#      script:
#        - go run main.go run dht/find-peers --builder=docker:go --runner=local:docker

# Services are not supported on Travis (Docker + Redis) when in Mac OS X
#    - stage: run
#      name: "dht/find-peers windows - with docker"
#      os: windows
#      script:
#        - go run main.go run dht/find-peers --builder=docker:go --runner=local:docker
