- name: Set TGRole label to manager and drain
  docker_node:
    hostname: "{{ inventory_hostname }}"
    labels:
      TGRole: manager

- name: Set TGRole label for workers
  docker_node:
    hostname: "{{ item }}"
    labels:
      TGRole: worker
  with_items: "{{ groups['role_worker'] }}"

- name: Set TGRole label for Redis
  docker_node:
    hostname: "{{ item }}"
    labels:
      TGRole: redis
  with_items: "{{ groups['role_redis'] }}"

