name = "benchmarks"
# hashicorp/go-getter URLs, so in the future we can support fetching test plans
# from GitHub.
source_path = "file://${TESTGROUND_SRCDIR}/plans/benchmarks"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.13"
module_path = "github.com/ipfs/testground/plans/benchmarks"
exec_pkg = "."

[builders."exec:go"]
enabled = true
module_path = "github.com/ipfs/testground/plans/benchmarks"
exec_pkg = "."

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "all"
instances = { min = 1, max = 20000, default = 1 }

  [testcases.params]
  barrier_iterations = { type = "int", desc = "number of iterations of the barrier test", unit = "iteration", default = 10 }
  subtree_iterations = { type = "int", desc = "number of iterations of the subtree test", unit = "iteration", default = 2000 }
  subtree_test_timeout_secs  = { type = "int", desc = "subtree testcase timeout", unit = "seconds", default = 300 }
  barrier_test_timeout_secs  = { type = "int", desc = "barrier testcase timeout", unit = "seconds", default = 300 }

[[testcases]]
name = "startup"
instances = { min = 1, max = 20000, default = 1 }

[[testcases]]
name = "netinit"
instances = { min = 1, max = 20000, default = 1 }

[[testcases]]
name = "netlinkshape"
instances = { min = 1, max = 20000, default = 1 }

[[testcases]]
name = "barrier"
instances = { min = 1, max = 50000, default = 1 }

  [testcases.params]
  barrier_iterations = { type = "int", desc = "number of iterations of the barrier test", unit = "iteration", default = 10 }
  barrier_test_timeout_secs  = { type = "int", desc = "barrier testcase timeout", unit = "seconds", default = 300 }

[[testcases]]
name = "subtree"
instances = { min = 1, max = 20000, default = 2 }

  [testcases.params]
  subtree_iterations = { type = "int", desc = "number of iterations of the subtree test", unit = "iteration", default = 2000 }
  subtree_test_timeout_secs  = { type = "int", desc = "subtree testcase timeout", unit = "seconds", default = 300 }
