---
# Changes from defaults:
# * override "fullname" so it is resolves with http://prometheus-pushgateway
#   This matches the behavior from the kops addon, but we don't need to do this
#   once we make this a configurable option.
# * enable the serviceMonitor, so it will be picked up by the prometheus
#   operator. Move the serviceMonitor to the default namespace.
# * Change the scrape interval to a short value. This should be set to the same
#   value with which plans push to the pushgatway. See the runner sdk.
# * Permissive network policy.
# * podAnnotations is set to flannel to force it to be ont he control network.
prometheus-pushgateway:
  fullnameOverride: prometheus-pushgateway
  serviceMonitor:
    enabled: true
    interval: 5s
    namespace: default
  networkPolicy:
    allowAll: true
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - redis
        topologyKey: "kubernetes.io/hostname"
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - prometheus-operator-operator
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    testground.nodetype: infra
  podAnnotations:
    cni: flannel
  resources:
    requests:
      memory: 2000Mi
      cpu: 1000m
    limits:
      memory: 2000Mi
      cpu: 1000m


# Changes from defaults:
# * enable redis exporter
# * enable the serviceMonitor so it will be picked up by prometheus
# * Disable cluster mode -- there are failure modes which could result in
#   dataloss after acknowledgement.
# * SecurityContext and sysctlImage provides tuning for redis to provide for 10k
# * Master resources is setup to be a large value so redis will be mostly
#   singele-tenant.
# * podAnnotations is set to flannel to force it to be on the control network.
redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: default
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 256Mi
        cpu: 200m
  cluster:
    enabled: false
  usePassword: false
  securityContext:
    sysctls:
      - name: net.core.somaxconn
        value: "131072"
      - name: net.netfilter.nf_conntrack_max
        value: "1048576"
  master:
    persistence:
      enabled: false
    extraFlags:
      - "--maxclients 131072"
    nodeSelector:
      testground.nodetype: infra
    podAnnotations:
      cni: flannel
    resources:
      requests:
        memory: 13000Mi
        cpu: 6500m
      limits:
        memory: 13000Mi
        cpu: 6500m
