name = "integrations"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "issue-1349-silent-failure"
instances = { min = 1, max = 1, default = 1 }

[[testcases]]
name = "issue-1493-success"
instances = { min = 1, max = 1000, default = 1 }

[[testcases]]
name = "issue-1493-optional-failure"
instances = { min = 1, max = 1000, default = 1 }
