# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  win: circleci/windows@2.4.0

workflows:
  version: 2
  test_os:
    jobs:
      - test-linux
      - test-windows
jobs:
  test-linux:
    machine:
      image: ubuntu-1604:201903-01
      # Docker layer caching requires payment: https://circleci.com/pricing/
      # docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "install go 1.14"
          command: |
            curl -o ~/go.tar.gz https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz
            tar -C ~/ -xzvf ~/go.tar.gz
            rm -rf ~/.go_workspace
            ln -s ~/go ~/.go_workspace 
      - run:
          name: "make tidy"
          command: make tidy && git diff --exit-code
      - run:
          name: "install linter"
          command: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.23.6
      - run:
          name: "make lint"
          command: make lint
      - run:
          name: "make  build-all"
          command: make build-all
      - run:
          name: "make sidecar"
          command: make docker-sidecar
      - run:
          name: "make test"
          command: |
            mkdir -p $HOME/testground/plans 
            ln -s $HOME/project/plans/placebo $HOME/testground/plans/placebo
            go test -v ./...

  # https://circleci.com/docs/2.0/executor-intro/#windows
  test-windows:
    executor: win/default
    steps:
      - checkout
      - run:
          name: "install go 1.14"
          command: |
            $wc = New-Object System.Net.WebClient
            $wc.DownloadFile("https://dl.google.com/go/go1.14.2.windows-amd64.msi" ".\go.msi")
            msiexec.exe .\go.msi
