# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "make tidy"
          command: make tidy && git diff --exit-code
      - run:
          name: "install linter"
          command: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.23.6
      - run:
          name: "make lint"
          command: make lint
      - run:
          name: "make sidecar"
          command: make docker-sidecar

      - run:
          name: "make test"
          command: go test -v ./...
