# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
orbs:
  win: circleci/windows@2.2.0

jobs:
  test-lin:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "install go 1.14"
          command: |
            curl -o ~/go.tar.gz https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz
            tar -C ~/ -xzvf ~/go.tar.gz
            rm -rf ~/.go_workspace
            ln -s ~/go ~/.go_workspace 
      - run:
          name: "make tidy"
          command: make tidy && git diff --exit-code
      - run:
          name: "install linter"
          command: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.23.6
      - run:
          name: "make lint"
          command: make lint
      - run:
          name: "make sidecar"
          command: make docker-sidecar

      - run:
          name: "make test"
          command: |
            mkdir -p $HOME/testground/plans 
            ln -s $HOME/project/plans/placebo $HOME/testground/plans/placebo
            go test -v ./...
  test-win:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
        name: "install go 1.14"
        command: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile("https://dl.google.com/go/go1.14.2.windows-amd64.msi","C:\tmp\go.msi")
workflows:
  version: 2
  lin_and_win:
    jobs:
      - test-lin
      - test-win
