apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: testground-sidecar
spec:
  selector:
    matchLabels:
      name: testground-sidecar
  template:
    metadata:
      labels:
        name: testground-sidecar
    spec:
      terminationGracePeriodSeconds: 10
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: testground-sidecar
        image: iptestground/sidecar:edge
        command: ["testground"]
        args: ["sidecar", "--runner", "mock"]
        ports:
        - name: sidecarhttp
          containerPort: 6060
        resources:
          limits:
            cpu: 20m
            memory: 26Mi
          requests:
            cpu: 20m
            memory: 26Mi
      nodeSelector:
        testground.node.role.plan: "true"

