name = "lotus-base-next-2020.07.14-8m"
source_path = "file://${TESTGROUND_SRCDIR}/plans/lotus-base-next-2020.07.14-8m"

[defaults]
builder = "docker:lotus"
runner = "local:docker"

[build_strategies."docker:lotus"]
enabled = true
go_version = "1.14"
module_path = "github.com/ipfs/testground/plans/lotus-base"
exec_pkg = "."
copy_lotus = true
lotus_path = "../lotus-next-2020.07.14-8m"

[run_strategies."local:docker"]
enabled = true

[run_strategies."cluster:k8s"]
enabled = true

# seq 0
[[testcases]]
name = "placeholder"
instances = { min = 1, max = 1, default = 1 }

