name = "lotus-js-testnet-v3-200509"
source_path = "file://${TESTGROUND_SRCDIR}/plans/lotus-js-testnet-v3-2020.05.09"

[defaults]
builder = "docker:lotus"
runner = "local:docker"

[build_strategies."docker:lotus"]
enabled = true
go_version = "1.13"
module_path = "github.com/ipfs/testground/plans/lotus-js-testnet-v3-2020.05.09"
exec_pkg = "."

[run_strategies."local:docker"]
enabled = true

[run_strategies."cluster:k8s"]
enabled = true

# seq 0
[[testcases]]
name = "bootstrap"
instances = { min = 1, max = 20000, default = 2 }

  [testcases.params]
  delay-between-starts = { type = "int", desc = "delay", unit = "milliseconds", default = 30000 }
  log-level = { type = "string", desc = "log level", default = "INFO" }
  keep-alive = { type = "boolean", desc = "keep alive after test done", default = false }
  ssh-tunnel = { type = "string", desc = "establish ssh tunnel to host", default = "" }

