apiVersion: v1
kind: LimitRange
metadata:
  name: default-pod-limits
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: 100m
    defaultRequest:
      memory: 256Mi
      cpu: 100m
    type: Container
