- name: create cronjob for cleaning up dangling docker resources
  become: yes
  cron:
      name: "docker-clean-up"
      minute: "{{ docker_cleanup_schedule[0] }}"
      hour: "{{ docker_cleanup_schedule[1] }}"
      day: "{{ docker_cleanup_schedule[2] }}"
      month: "{{ docker_cleanup_schedule[3] }}"
      weekday: "{{ docker_cleanup_schedule[4] }}"
      job: "docker system prune -f &>/dev/null"
