[runners."local:docker"]
disabled = true

[daemon]
listen = ":8040"

[daemon.scheduler]
task_timeout_min = 5
task_repo_type = "disk"

[client]
endpoint = "http://localhost:8040"
user = "tg_integration_test"