# Test for https://github.com/testground/testground/issues/1493
[metadata]
name = "issue-1493-multiple-runs-happy-path"

[global]
  builder = "docker:go"
  plan = "integrations"
  case = "issue-1493-success"
  runner = "local:docker"

  [global.build_config]
    docker_build_image = "golang:1.16-buster"

[[groups]]
  id = "group_simple"
  instances = {count = 1}

[[runs]]
  id = "run_simple_1"

  [[runs.groups]]
  id = "group_simple"
  instances = {count = 1}

[[runs]]
  id = "run_simple_2"

  [[runs.groups]]
  id = "group_simple"
  instances = {count = 1}

  [[runs.groups]]
  id = "another_group"
  group_id = "group_simple"
  instances = {count = 1}

[[runs]]
  id = "run_simple_4"

  [[runs.groups]]
  id = "group_simple"
  # todo: add group_id and default group_id to id. This will let use define a group name in here.
  instances = {count = 4}