# Test for https://github.com/testground/testground/issues/1357
# Introduces:
#  - `builder' option per group
#  - `path` option for generic and docker builders
[metadata]
  name = "issue-1412-path-and-go-dependencies"

[global]
  plan = "integrations_mixed_builders"
  case = "issue-1412-path-and-go-dependencies"
  total_instances = 1
  runner = "local:docker"

[[groups]]
  id = "go"
  instances = { count = 1 }
  builder = "docker:go"

  [groups.build_config]
    path = "go/"

  [groups.build_config.dockerfile_extensions]
    pre_build = "RUN cd ${PLAN_DIR} && go mod download github.com/testground/sdk-go && go mod tidy"

    [[groups.build.dependencies]]
      module = "github.com/testground/sdk-go"
      version = "master"
