global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'prometheus-pushgateway'
    static_configs:
      - targets: ['prometheus-pushgateway:9091']

  - job_name: 'redis'
    static_configs:
      - targets: ['testground-redis']
