name = "integrations"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "issue-1357-mix-builder-configuration"
instances = { min = 2, max = 100, default = 2 }

[testcases.params]
  expected_implementation = { type = "string", desc = "expected implementation" }

[[testcases]]
name = "issue-1412-path-and-go-dependencies"
instances = { min = 1, max = 1, default = 1 }
