---
- hosts: localhost
  remote_user: ubuntu
  gather_facts: yes
  tasks:
    - name: Set manager
      set_fact:
        manager: "{{ ansible_facts.default_ipv4.address }}"
    - name: Manager IP
      debug:
        msg: "{{ manager }}"
    - name: tg_hosts
      debug:
        msg: "{{ groups[tg_hosts] }}"
    - name: Set new_hosts
      set_fact:
        new_hosts: "{{ [ manager ] | union(groups[tg_hosts]) }}"
        manager: "{{ ansible_facts.default_ipv4.address }}"
    - name: tg_hosts reordered
      debug:
        msg: "{{ new_hosts }}"
    - name: Set manager_hosts
      set_fact:
        manager_hosts: "{{ groups[tg_hosts] | intersect(groups['tag_TGRole_manager']) }}"
    - name: Dump manager_hosts
      debug:
        msg: "{{ manager_hosts }}"
    - name: Set redis_hosts
      set_fact:
        redis_hosts: "{{ groups[tg_hosts] | intersect(groups['tag_TGRole_redis']) }}"
    - name: Dump redis_hosts
      debug:
        msg: "{{ redis_hosts }}"
    - name: Set worker_hosts
      set_fact:
        worker_hosts: "{{ groups[tg_hosts] | intersect(groups['tag_TGRole_worker']) }}"
    - name: Dump worker_hosts
      debug:
        msg: "{{ worker_hosts }}"
    - name: generate inventory file from template
      template:
        src: inventory.ini.j2
        dest: inventory.ini
