---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Generate ssh key for local access
      openssh_keypair:
        path: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
    - name: Add key to authorized_keys
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
