name = "additional_hosts"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "additional_hosts"
instances = { min = 1, max = 1, default = 1 }
