kind: Pod
apiVersion: v1
metadata:
  name: test-pod-sleep2
spec:
  containers:
  - name: test-pod-sleep2
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "sleep 60000"
    volumeMounts:
      - name: efs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: efs
