[metadata]
  name = "find-provs"
  author = "adin"

[global]
  plan = "dht"
  case = "find-providers"
  total_instances = 150
  builder = "docker:go"
  runner = "cluster:k8s"
  [global.build_config]
    push_registry = true
    registry_type = "aws"

[[groups]]
  id = "balsam-undialable-provider"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:96573c154cdb"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      expect_dht = "false"
      group_order = "4"
      latency = "2000"
      record_count = "1"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-undialable-searcher"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:96573c154cdb"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      expect_dht = "false"
      group_order = "5"
      latency = "2000"
      search_records = "true"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-dialable-passive"
  [groups.instances]
    count = 80
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:96573c154cdb"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      expect_dht = "false"
      group_order = "6"
      latency = "2000"
      timeout_secs = "600"
      undialable = "false"

[[groups]]
  id = "balsam-dialable-provider"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:96573c154cdb"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      expect_dht = "false"
      group_order = "7"
      latency = "2000"
      record_count = "1"
      timeout_secs = "600"
      undialable = "false"

[[groups]]
  id = "balsam-dialable-searcher"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:96573c154cdb"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      expect_dht = "false"
      group_order = "8"
      latency = "2000"
      search_records = "true"
      timeout_secs = "600"
      undialable = "false"

[[groups]]
  id = "cypress-passive"
  [groups.instances]
    count = 35
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "1506cc0533d2548eccaf006ea4ab57c9134ad2ce"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.3-0.20200330204848-85060e8d229f"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-xor"
      version = "df24f5b04bcbdc0059b27989163a6090f4f6dc7a"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:7cce136bde19"
    [groups.run.test_params]
      alpha = "6"
      beta = "1"
      bs_strategy = "3"
      bucket_size = "10"
      group_order = "1"
      latency = "2000"
      timeout_secs = "600"

[[groups]]
  id = "cypress-provider"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "1506cc0533d2548eccaf006ea4ab57c9134ad2ce"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.3-0.20200330204848-85060e8d229f"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-xor"
      version = "df24f5b04bcbdc0059b27989163a6090f4f6dc7a"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:7cce136bde19"
    [groups.run.test_params]
      alpha = "6"
      beta = "1"
      bs_strategy = "3"
      bucket_size = "10"
      group_order = "2"
      latency = "2000"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "cypress-searcher"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "1506cc0533d2548eccaf006ea4ab57c9134ad2ce"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.3-0.20200330204848-85060e8d229f"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-xor"
      version = "df24f5b04bcbdc0059b27989163a6090f4f6dc7a"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:7cce136bde19"
    [groups.run.test_params]
      alpha = "6"
      beta = "1"
      bs_strategy = "3"
      bucket_size = "10"
      group_order = "3"
      latency = "2000"
      search_records = "true"
      timeout_secs = "600"

[[groups]]
  id = "cypress-bs"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "1506cc0533d2548eccaf006ea4ab57c9134ad2ce"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.3-0.20200330204848-85060e8d229f"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-xor"
      version = "df24f5b04bcbdc0059b27989163a6090f4f6dc7a"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:7cce136bde19"
    [groups.run.test_params]
      alpha = "6"
      beta = "1"
      bootstrapper = "true"
      bs_strategy = "1"
      bucket_size = "10"
      group_order = "0"
      latency = "2000"
      timeout_secs = "600"
