## THIS IS AN EXAMPLE COMPOSITION
##
## It performs a run of the dht/find-peers test case, with 100 instances:
##
##  * 10 of them are boostrappers, with upstream dependency overrides.
##  * 45% are DHT clients.
##  * 45% are DHT servers.
##
[metadata]
name    = "find-peers-01"
author  = "raulk"

[global]
plan    = "dht"
case    = "find-peers"
builder = "docker:go"
runner  = "cluster:k8s"

total_instances = 100

[[groups]]
id = "bootstrappers"
instances = { count = 10 }

  [groups.build]
  dependencies = [
      { module = "github.com/libp2p/go-libp2p-kad-dht", version = "995fee9e5345fdd7c151a5fe871252262db4e788"},
      { module = "github.com/libp2p/go-libp2p", version = "76944c4fc848530530f6be36fb22b70431ca506c"},
  ]

  [groups.run]
  test_params = { random_walk = true, n_bootstrap = 10 }

[[groups]]
id = "servers"
instances = { percentage = 0.45 }

  [groups.run]
  test_params = { client = false, random_walk = true, n_bootstrap = 10 }

[[groups]]
id = "clients"
instances = { percentage = 0.45 }

  [groups.run]
  test_params = { client = true, random_walk = true, n_bootstrap = 10 }
