[metadata]
  name = "find-provs"
  author = "adin"

[global]
  plan = "dht"
  case = "find-providers"
  total_instances = 150
  builder = "docker:go"
  runner = "local:docker"

[[groups]]
  id = "balsam-undialable-provider"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "838eef15f953"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      record_count = "1"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-undialable-searcher"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "a5869bff0453"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      search_records = "true"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-dialable-passive"
  [groups.instances]
    count = 80
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "bdac6c678253"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      timeout_secs = "600"
      undialable = "false"

[[groups]]
  id = "balsam-dialable-provider"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "33395aac1d27"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      record_count = "1"
      timeout_secs = "600"
      undialable = "false"

[[groups]]
  id = "balsam-dialable-searcher"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "9ae7dc357a74"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      search_records = "true"
      timeout_secs = "600"
      undialable = "false"

[[groups]]
  id = "cypress-passive"
  [groups.instances]
    count = 35
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "1a8a5f6fc994993322a9bed5b19ce092b5ca9537"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "00b84c7b63af"
    [groups.run.test_params]
      alpha = "6"
      bs_strategy = "3"
      bucket_size = "10"
      timeout_secs = "600"

[[groups]]
  id = "cypress-provider"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "1a8a5f6fc994993322a9bed5b19ce092b5ca9537"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "e64521f25e2a"
    [groups.run.test_params]
      alpha = "6"
      bs_strategy = "3"
      bucket_size = "10"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "cypress-searcher"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "1a8a5f6fc994993322a9bed5b19ce092b5ca9537"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "37aacc67ccc6"
    [groups.run.test_params]
      alpha = "6"
      bs_strategy = "3"
      bucket_size = "10"
      search_records = "true"
      timeout_secs = "600"

[[groups]]
  id = "cypress-bs"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "1a8a5f6fc994993322a9bed5b19ce092b5ca9537"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "105dabf50c07"
    [groups.run.test_params]
      alpha = "6"
      bootstrapper = "true"
      bs_strategy = "1"
      bucket_size = "10"
      timeout_secs = "600"
