[metadata]
  name = "find-provs"
  author = "adin"

[global]
  plan = "dht"
  case = "find-providers"
  total_instances = 2170
  builder = "docker:go"
  runner = "cluster:k8s"
  [global.build_config]
    push_registry = true
    registry_type = "aws"

[[groups]]
  id = "cypress-passive"
  [groups.instances]
    count = 2020
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "28ea636110d3177d60fa0f243cde67c288204f0f"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:2bb1237d3e09"
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "1"
      latency = "100"
      timeout_secs = "600"

[[groups]]
  id = "cypress-provider-small"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "28ea636110d3177d60fa0f243cde67c288204f0f"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:2bb1237d3e09"
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "4"
      latency = "100"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "cypress-provider-medium"
  [groups.instances]
    count = 15
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "28ea636110d3177d60fa0f243cde67c288204f0f"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:2bb1237d3e09"
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "3"
      latency = "100"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "cypress-provider-large"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "28ea636110d3177d60fa0f243cde67c288204f0f"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:2bb1237d3e09"
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "2"
      latency = "100"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "cypress-searcher"
  [groups.instances]
    count = 25
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "28ea636110d3177d60fa0f243cde67c288204f0f"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:2bb1237d3e09"
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "5"
      latency = "100"
      search_records = "true"
      timeout_secs = "600"

[[groups]]
  id = "cypress-bs"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "28ea636110d3177d60fa0f243cde67c288204f0f"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:2bb1237d3e09"
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "0"
      latency = "100"
      timeout_secs = "600"
