[metadata]
  name = "gcp"
  author = "adin"

[global]
  plan = "dht"
  case = "get-closest-peers"
  total_instances = 800
  builder = "docker:go"
  runner = "cluster:k8s"
  [global.build_config]
    push_registry = true
    registry_type = "aws"

[[groups]]
  id = "cypress-passive"
  [groups.instances]
    count = 775
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "12db17a86ca7f8be9b6166990fd874bf7d4e665e"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:bb35ace44ee3"
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "1"
      latency = "100"
      timeout_secs = "600"

[[groups]]
  id = "cypress-searcher"
  [groups.instances]
    count = 20
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "12db17a86ca7f8be9b6166990fd874bf7d4e665e"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:bb35ace44ee3"
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "2"
      latency = "100"
      record_count = "1"
      search_records = "true"
      timeout_secs = "600"

[[groups]]
  id = "cypress-bs"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "12db17a86ca7f8be9b6166990fd874bf7d4e665e"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.7.1-0.20200324235900-45048e60077c"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:bb35ace44ee3"
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "0"
      latency = "100"
      timeout_secs = "600"
