name = "verify"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "uses-data-network"
instances = { min = 1, max = 200, default = 1 }
