name = "verify"
# hashicorp/go-getter URLs, so in the future we can support fetching test plans
# from GitHub.
source_path = "file://${TESTGROUND_SRCDIR}/plans/verify"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true
go_version = "1.13"
module_path = "github.com/testground/testground/plans/placebo"
exec_pkg = "."

[runners."local:docker"]
enabled = true

[[testcases]]
name = "uses-data-network"
instances = { min = 1, max = 200, default = 1 }
