name = "placebo"
# hashicorp/go-getter URLs, so in the future we can support fetching test plans
# from GitHub.
source_path = "file://${TESTGROUND_SRCDIR}/plans/placebo"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.13"
module_path = "github.com/testground/testground/plans/placebo"
exec_pkg = "."

[builders."exec:go"]
enabled = true
module_path = "github.com/testground/testground/plans/placebo"
exec_pkg = "."

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[[testcases]]
name = "ok"
instances = { min = 1, max = 200, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "abort"
instances = { min = 1, max = 250, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "metrics"
instances = { min = 1, max = 250, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "panic"
instances = { min = 1, max = 250, default = 1 }

[[testcases]]
name = "stall"
instances = { min = 1, max = 250, default = 1 }
