ansible_user: ubuntu

# geerlingguy.docker
docker_users:
  - ubuntu

filebeat:
  version: 7.x
  cloud_id: "{{ lookup('onepassword', 'Filebeat configuration', field='filebeat_cloud_id', vault='Test Infra') }}"
  cloud_auth: "{{ lookup('onepassword', 'Filebeat configuration', field='filebeat_cloud_auth', vault='Test Infra') }}"
