name: Testground Publish (edge)
on:
  push:
    branches:
      - master

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.16.x"
        cache: true
    - name: Build Testground
      run: go build -ldflags "-X github.com/testground/testground/pkg/version.GitCommit=`git rev-list -1 HEAD`" .
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: testground-release
        path: |
          ./testground
          ./static

  docker:
    runs-on: ubuntu-latest
    env:
      ORGANIZATION: iptestground
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "${{ env.ORGANIZATION }}/testground:edge"
          file: ./Dockerfile.testground
          platforms: linux/arm64,linux/amd64
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "${{ env.ORGANIZATION }}/sidecar:edge"
          file: ./Dockerfile.sidecar
          platforms: linux/arm64,linux/amd64
