apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dummy
  namespace: default
  labels:
    k8s-app: dummy
spec:
  selector:
    matchLabels:
      name: dummy
  template:
    metadata:
      annotations:
        cni: "flannel"
      labels:
        name: dummy
    spec:
      volumes:
      - name: host-sys
        hostPath:
          path: /sys
      initContainers:
      - name: disable-thp
        image: busybox
        volumeMounts:
          - name: host-sys
            mountPath: /host-sys
        command: ["sh", "-c", "echo never >/host-sys/kernel/mm/transparent_hugepage/enabled"]
      containers:
      - name: dummy
        command: ["/bin/sleep", "3650d"]
        image: governmentpaas/curl-ssl
