---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  annotations:
    cni: "flannel,weave"
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: node
            operator: In
            values:
            - first
        topologyKey: kubernetes.io/hostname
  containers:
  - name: pod2
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: nonsens3/netcat
    ports:
    - containerPort: 80
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN", "SYS_TIME"]
      privileged: true
