apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: weave-net
  name: weave-net
spec:
  clusterIP: None
  ports:
  - name: weave-metrics
    port: 6782
    targetPort: 6782
  selector:
    name: weave-net
